# redfish-bmc-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redfish-bmc-credentials
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=  # base64编码的admin
  password: MHBlbkJtYy4=  # base64编码的0penBmc.，请在生产环境中更改